### ISSUE TITLE
Compilation failed, prompt: ld: framework not found MAMapKit, how to solve it?

### ISSUE THREAD

**Issue by Travis990** [Mclarenyang/BikeDemo#2]
![image](https://user-images.githubusercontent.com/6883210/60314826-a0987180-9996-11e9-83ae-936d1338ab1e.png)

**Comment by PiotrNewt** [comment]
抱歉回得这么晚
建议删除 framwork 文件，clean后重新添加
参考[stackoverflow](https://stackoverflow.com/questions/32687105/framework-not-found-in-xcode)上相似的问题

-----
Sorry for replying so late. 
I suggest removing the framwork file and re-adding it.
Referring to the [similar issue](https://stackoverflow.com/questions/32687105/framework-not-found-in-xcode) on stackoverflow.

**Comment by PiotrNewt** [comment]
Because there is no discussion about this issue, it will be closed！
